name: Feature Request
description: Suggest a new feature or enhancement for SmartVillage
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your idea.
  
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Describe the feature...
    validations:
      required: true
  
  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What is the use case?
      placeholder: Explain the problem or use case...
    validations:
      required: true
  
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
      placeholder: Describe your proposed solution...
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've considered...
    validations:
      required: false
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking core functionality)
        - High (Important for user experience)
        - Medium (Nice to have)
        - Low (Minor enhancement)
    validations:
      required: true
  
  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area of the application does this feature relate to?
      options:
        - User Interface/UX
        - Backend/API
        - Database
        - Authentication/Authorization
        - Performance
        - Security
        - Documentation
        - Other
    validations:
      required: true
  
  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Designs
      description: If applicable, add mockups, wireframes, or design ideas
      placeholder: Drag and drop images here or paste image URLs
    validations:
      required: false
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, examples, or references about the feature request here.
      placeholder: Any additional information...
    validations:
      required: false
  
  - type: checkboxes
    id: willingness-to-contribute
    attributes:
      label: Willingness to Contribute
      description: Are you willing to contribute to implementing this feature?
      options:
        - label: I am willing to submit a PR for this feature
          required: false
