name: Refactor/Improvement
description: Suggest code refactoring or technical improvements for SmartVillage
title: "[Refactor]: "
labels: ["refactor", "technical-debt"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a refactoring or improvement! Please provide details about the technical debt or code improvements you'd like to see.
  
  - type: textarea
    id: current-situation
    attributes:
      label: Current Situation
      description: Describe the current state of the code or architecture that needs improvement.
      placeholder: Describe what currently exists...
    validations:
      required: true
  
  - type: textarea
    id: problem-description
    attributes:
      label: Problem/Issues
      description: What are the issues with the current implementation?
      placeholder: |
        - Poor performance
        - Hard to maintain
        - Code duplication
        - etc.
    validations:
      required: true
  
  - type: textarea
    id: proposed-improvement
    attributes:
      label: Proposed Improvement
      description: What refactoring or improvements do you suggest?
      placeholder: Describe the proposed changes...
    validations:
      required: true
  
  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What benefits will this refactoring provide?
      placeholder: |
        - Better performance
        - Improved maintainability
        - Reduced code complexity
        - etc.
    validations:
      required: true
  
  - type: dropdown
    id: impact-scope
    attributes:
      label: Impact Scope
      description: How much of the codebase will this refactoring affect?
      options:
        - Small (Single file/component)
        - Medium (Multiple files/components)
        - Large (Module/feature)
        - Very Large (System-wide changes)
    validations:
      required: true
  
  - type: dropdown
    id: refactor-type
    attributes:
      label: Refactor Type
      description: What type of refactoring is this?
      options:
        - Code cleanup/simplification
        - Performance optimization
        - Architecture improvement
        - Code duplication removal
        - Better error handling
        - Type safety improvement
        - Testing improvements
        - Documentation
        - Dependency updates
        - Other
    validations:
      required: true
  
  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How urgent is this refactoring?
      options:
        - Critical (Causing issues)
        - High (Should be done soon)
        - Medium (Nice to have)
        - Low (Can wait)
    validations:
      required: true
  
  - type: textarea
    id: affected-files
    attributes:
      label: Affected Files/Modules
      description: List the files or modules that would be affected by this refactoring
      placeholder: |
        - /my-app/app/components/...
        - /my-app/lib/...
    validations:
      required: false
  
  - type: textarea
    id: breaking-changes
    attributes:
      label: Potential Breaking Changes
      description: Will this refactoring introduce any breaking changes?
      placeholder: Describe any potential breaking changes...
    validations:
      required: false
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, code examples, or references about the refactoring here.
      placeholder: Any additional information...
    validations:
      required: false
  
  - type: checkboxes
    id: willingness-to-contribute
    attributes:
      label: Willingness to Contribute
      description: Are you willing to contribute to implementing this refactoring?
      options:
        - label: I am willing to submit a PR for this refactoring
          required: false
